name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      # - uses: actions/checkout@v1

      # - name: Copy repository contents via scp
      #   uses: appleboy/scp-action@master
      #   env:
      #     HOST: ${{ secrets.HOST }}
      #     USERNAME: ${{ secrets.USERNAME }}
      #     PORT: ${{ secrets.PORT }}
      #     KEY: ${{ secrets.SSHKEY }}
      #   with:
      #     source: "."
      #     target: "/home/dev2"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd /home/dev2/ |
            git pull |
            ls -al

      # - uses: actions/checkout@v3

      # - name: Build Updated Docker Compose Environment
      #   run: docker compose -f /home/dev2/solution_github/production.yml build

      # - name: Stop Old Docker Compose Environment
      #   run: docker compose -f /home/dev2/solution_github/production.yml down

      # - name: Run Updated Docker Compose Environment
      #   run: docker compose -f /home/dev2/solution_github/production.yml up -d

      # - name: Remove Unused Docker Compose Environment
      #   run: |
      #     docker container prune -f
      #     docker image prune -f
